apiVersion: v1
kind: Service
metadata:
  name: "flask-svc-alb-green"
  namespace: "flask-alb"
spec:
  selector:
    app: "flask-deploy-alb-green"
  type: NodePort
  ports:
    - name: web
      port: 8080
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: "flask"
  name: "flask-deploy-alb-green"
  namespace: "flask-alb"
spec:
  selector:
    matchLabels:
      app: "flask-deploy-alb-green"
  replicas: 1
  template:
    metadata:
      labels:
        app: "flask-deploy-alb-green"
    spec:
      containers:
      - name: "flask"
        image: public.ecr.aws/p8v8e7e5/myartifacts:flask-image-grey
        ports:
          - containerPort: 5000
        resources:
          limits:
            memory: "500Mi"
            cpu: "0.25"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
